#!/bin/sh

export HOME=/home/reddit
cd $HOME/reddit/r2
exec 2>&1
exec setuidgid reddit /usr/local/bin/paster run run.ini -c "from r2.lib.db import queries; queries.process_votes(queries.vote_comment_q, limit=100)"
