#!/bin/bash

command=${UPSTART_JOB#reddit-consumers-}
for consumer in $REDDIT_CONSUMER_CONFIG/*; do
    instance_count=$(cat $REDDIT_CONSUMER_CONFIG/$consumer)

    # allow targeting which consumer the event is meant for (defaulting to 'all')
    if [ ! -z "$TARGET" -a "x$TARGET" != "xall" -a "x$TARGET" != "x$consumer" ]; then
        continue
    fi

    for i in $(seq 1 "$instance_count"); do
        "/sbin/$command" "reddit-consumer-$consumer" "x=$i"
    done
done

